name: Delete All History

on:
  workflow_dispatch: # 建议只保留手动触发，点击按钮即可清洗

jobs:
  purge_history:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete ALL workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          
          # 关键配置：全部设为 0，表示一个不留
          retain_days: 0
          keep_minimum_runs: 0
          
          # 关键配置：指定删除所有状态（默认只删 success/skipped，必须加上 failure）
          delete_run_by_conclusion_pattern: "cancelled, skipped, success, failure"
